"""Search-layer execution defaults outside the project settings surface."""

from __future__ import annotations

DEFAULT_SEARCH_MAX_RESULTS_PER_QUERY = 5
DEFAULT_SEARCH_SCRAPE_TIMEOUT_S = 20
DEFAULT_SEARCH_PROVIDER_TIMEOUT_S = 6.0
DEFAULT_SEARCH_TOTAL_TIMEOUT_S = 12.0
DEFAULT_SEARCH_READ_TIMEOUT_S = 10.0
DEFAULT_SEARCH_PARALLEL_RETRIEVERS = True
DEFAULT_SEARCH_MAX_PARALLEL_RETRIEVERS = 4
DEFAULT_SEARCH_FUSION_K = 60
DEFAULT_SEARCH_RUNTIME_CACHE_ENABLED = True
DEFAULT_SEARCH_RUNTIME_CACHE_TTL_S = 900
DEFAULT_SEARCH_RUNTIME_CACHE_MAX_ENTRIES = 256

__all__ = [
    "DEFAULT_SEARCH_FUSION_K",
    "DEFAULT_SEARCH_MAX_PARALLEL_RETRIEVERS",
    "DEFAULT_SEARCH_MAX_RESULTS_PER_QUERY",
    "DEFAULT_SEARCH_PARALLEL_RETRIEVERS",
    "DEFAULT_SEARCH_PROVIDER_TIMEOUT_S",
    "DEFAULT_SEARCH_READ_TIMEOUT_S",
    "DEFAULT_SEARCH_RUNTIME_CACHE_ENABLED",
    "DEFAULT_SEARCH_RUNTIME_CACHE_MAX_ENTRIES",
    "DEFAULT_SEARCH_RUNTIME_CACHE_TTL_S",
    "DEFAULT_SEARCH_SCRAPE_TIMEOUT_S",
    "DEFAULT_SEARCH_TOTAL_TIMEOUT_S",
]
