"""Generate Mermaid workflow diagrams for the current workflow modules."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[2]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.workflows.common.topology import WorkflowDiagramSpec, render_mermaid_flowchart
from app.workflows.digest.diagrams import WORKFLOW_DIAGRAMS as DIGEST_WORKFLOW_DIAGRAMS
from app.workflows.ingest.diagrams import WORKFLOW_DIAGRAMS as INGEST_WORKFLOW_DIAGRAMS

DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent / ".generated_workflow_diagrams"
WORKFLOW_REGISTRY = {
    diagram.key: diagram
    for diagram in (*INGEST_WORKFLOW_DIAGRAMS, *DIGEST_WORKFLOW_DIAGRAMS)
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Mermaid workflow diagrams from shared workflow topology specs.",
    )
    parser.add_argument(
        "--modules",
        nargs="*",
        default=["all"],
        help=f"Available modules: all, {', '.join(sorted(WORKFLOW_REGISTRY))}",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where markdown diagrams will be written.",
    )
    return parser.parse_args()


def resolve_requested_modules(modules: list[str]) -> list[str]:
    if not modules or "all" in modules:
        return sorted(WORKFLOW_REGISTRY)

    invalid_modules = [module for module in modules if module not in WORKFLOW_REGISTRY]
    if invalid_modules:
        valid = ", ".join(sorted(WORKFLOW_REGISTRY))
        invalid = ", ".join(invalid_modules)
        raise ValueError(f"Unknown modules: {invalid}. Available values: all, {valid}")

    return modules


def build_markdown(diagram: WorkflowDiagramSpec) -> str:
    description_block = f"{diagram.description}\n\n" if diagram.description else ""
    mermaid = render_mermaid_flowchart(diagram)
    return (
        f"# {diagram.title}\n\n"
        f"{description_block}"
        "```mermaid\n"
        f"{mermaid}\n"
        "```\n"
    )


def write_diagrams(*, output_dir: Path, module_keys: list[str]) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written_paths: list[Path] = []
    index_lines = [
        "# Workflow Diagrams",
        "",
        "Generated by `backend/app/scripts/generate_workflow_diagrams.py`.",
        "",
    ]

    for module_key in module_keys:
        diagram = WORKFLOW_REGISTRY[module_key]
        output_path = output_dir / f"{module_key}.md"
        output_path.write_text(build_markdown(diagram), encoding="utf-8")
        written_paths.append(output_path)
        index_lines.append(f"- [{diagram.title}]({output_path.name})")

    readme_path = output_dir / "README.md"
    readme_path.write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    written_paths.append(readme_path)
    return written_paths


def main() -> int:
    args = parse_args()
    try:
        module_keys = resolve_requested_modules(args.modules)
    except ValueError as exc:
        print(str(exc))
        return 1

    written_paths = write_diagrams(output_dir=args.output_dir, module_keys=module_keys)
    print("Generated workflow diagram files:")
    for path in written_paths:
        print(f"- {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
