import { defineConfig } from "orval"
import { readdir, readFile, stat, writeFile } from "node:fs/promises"
import path from "node:path"

const generatedHeader = ({ title, description }) => [
    "Generated by orval.",
    "Do not edit manually.",
    title,
    description,
].filter(Boolean)

async function collectTypeScriptFiles(target) {
    const targetStat = await stat(target)
    if (!targetStat.isDirectory()) {
        return target.endsWith(".ts") ? [target] : []
    }
    const entries = await readdir(target, { withFileTypes: true })
    const nested = await Promise.all(entries.map((entry) => (
        collectTypeScriptFiles(path.join(target, entry.name))
    )))
    return nested.flat()
}

async function normalizeGeneratedEof(targets) {
    const nested = await Promise.all(targets.map(collectTypeScriptFiles))
    const files = new Set(nested.flat())
    await Promise.all([...files].map(async (file) => {
        const content = await readFile(file, "utf8")
        const normalized = `${content.trimEnd()}\n`
        if (normalized !== content) {
            await writeFile(file, normalized, "utf8")
        }
    }))
}

export default defineConfig({
    api: {
        input: "./openapi.json",

        hooks: {
            afterAllFilesWrite: normalizeGeneratedEof,
        },

        output: {
            mode: "tags",

            clean: true,

            target: "./src/api/generated/endpoints.ts",

            schemas: "./src/api/generated/model",

            client: "react-query",

            override: {
                header: generatedHeader,
                mutator: {
                    path: "./src/api/client.ts",
                    name: "orvalApiClient",
                },
            },
        },
    },
})
