import { defineConfig } from "orval"

const generatedHeader = ({ title, description }) => [
    "Generated by orval.",
    "Do not edit manually.",
    title,
    description,
].filter(Boolean)

export default defineConfig({
    api: {
        input: "./openapi.json",

        output: {
            mode: "tags",

            target: "./src/api/generated/endpoints.ts",

            schemas: "./src/api/generated/model",

            client: "react-query",

            override: {
                header: generatedHeader,
                mutator: {
                    path: "./src/api/client.ts",
                    name: "orvalApiClient",
                },
            },
        },
    },
})
