"""DocGen runtime defaults that should stay code-owned within the lane."""

from __future__ import annotations

DEFAULT_DOCGEN_IO_PARALLELISM = 8
DEFAULT_DOCGEN_MAX_RESEARCH_QUERIES = 3
DEFAULT_DOCGEN_RETRIEVAL_TIMEOUT_S = 18.0
DEFAULT_DOCGEN_READ_TIMEOUT_S = 12.0

__all__ = [
    "DEFAULT_DOCGEN_IO_PARALLELISM",
    "DEFAULT_DOCGEN_MAX_RESEARCH_QUERIES",
    "DEFAULT_DOCGEN_READ_TIMEOUT_S",
    "DEFAULT_DOCGEN_RETRIEVAL_TIMEOUT_S",
]
