"""Digest Engine 提示词模块。

集中导出系统提示词与模板映射，其他模块可直接 from prompts import。
"""

from .prompts import PROMPTS, SYSTEM_PROMPT_OUTLINE_EXTRACT
from .kg_prompts import (
    KG_PROMPTS,
    SYSTEM_PROMPT_KG_EXTRACT,
    USER_PROMPT_KG_EXTRACT,
    SYSTEM_PROMPT_KG_ENTITY_MATCH,
    USER_PROMPT_KG_ENTITY_MATCH,
    SYSTEM_PROMPT_KG_UNIT_NAMING,
    USER_PROMPT_KG_UNIT_NAMING,
    SYSTEM_PROMPT_KG_THEME_TREE,
    USER_PROMPT_KG_THEME_TREE,
)

__all__ = [
    "SYSTEM_PROMPT_OUTLINE_EXTRACT",
    "PROMPTS",
    "KG_PROMPTS",
    "SYSTEM_PROMPT_KG_EXTRACT",
    "USER_PROMPT_KG_EXTRACT",
    "SYSTEM_PROMPT_KG_ENTITY_MATCH",
    "USER_PROMPT_KG_ENTITY_MATCH",
    "SYSTEM_PROMPT_KG_UNIT_NAMING",
    "USER_PROMPT_KG_UNIT_NAMING",
    "SYSTEM_PROMPT_KG_THEME_TREE",
    "USER_PROMPT_KG_THEME_TREE",
]
