"""兼容性 shim — 实际实现已移至 app.teaching.memory。"""
from app.teaching.memory import (  # noqa: F401
    LearningLogEntry,
    MemoryEntry,
    MemoryTag,
    UserProfile,
    append_to_learner_section,
    forget,
    get_learner_doc_path,
    get_learning_log,
    get_user_profile,
    load_doc_to_context,
    read_learner_doc,
    read_learner_section,
    recall,
    remember,
    sync_profile_to_doc,
    update_learner_section,
    write_learner_doc,
)
