export const SETTINGS_STYLES = {
  panel: {
    root: "fixed inset-0 z-[100]",
    backdrop: "absolute inset-0 modal-backdrop modal-backdrop-strong",
    viewport: "pointer-events-none absolute inset-0 flex items-center justify-center p-4 sm:p-6",
    dialog:
      "pointer-events-auto flex h-[85vh] w-full max-w-[1024px] overflow-hidden rounded-2xl bg-white shadow-[0_12px_28px_rgba(0,0,0,0.08)] ring-1 ring-zinc-200/70",
    body: "flex min-w-0 flex-1 flex-col bg-white",
    header: "flex items-center justify-between border-b border-zinc-100 px-8 py-5",
    headerTitle: "text-lg font-bold text-zinc-900 tracking-tight",
    headerDescription: "mt-1 text-sm text-zinc-500",
    closeButton:
      "inline-flex h-8 w-8 items-center justify-center rounded-full text-zinc-400 transition-colors hover:bg-zinc-100 hover:text-zinc-900 active:scale-95",
    closeIcon: "h-5 w-5",
    scrollArea: "min-h-0 flex-1 overflow-y-auto px-8 py-8 sm:px-12 settings-scroll",
    sectionFrame: "max-w-[760px] mx-auto",
  },
  nav: {
    root: "flex w-[240px] shrink-0 flex-col border-r border-zinc-100 bg-zinc-50/35 pt-2",
    header: "px-6 pb-2 pt-6",
    title: "text-xs font-semibold text-zinc-500",
    list: "flex-1 space-y-0.5 overflow-y-auto px-4 py-2",
    item:
      "group relative flex min-w-0 w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[14px] transition-colors overflow-hidden",
    itemActive: "bg-zinc-200/60 font-semibold text-zinc-900",
    itemIdle: "font-medium text-zinc-600 hover:bg-zinc-200/40 hover:text-zinc-900",
    itemIcon: "inline-flex shrink-0 items-center justify-center",
    itemIconActive: "text-zinc-900",
    itemIconIdle: "text-zinc-400 group-hover:text-zinc-500",
    itemIconSize: "h-4 w-4",
    itemLabel: "truncate leading-none",
    statusCard: "hidden",
    statusContent: "flex flex-col gap-2",
    statusLabel: "text-[11px] font-bold uppercase tracking-wider text-zinc-400",
    statusRow: "flex items-center gap-2",
    statusText: "text-[13px] font-semibold text-zinc-700",
    runtimeIndicatorWrap: "relative flex h-2 w-2",
    runtimeIndicatorPulse:
      "absolute inline-flex h-full w-full animate-ping rounded-full opacity-75",
    runtimeIndicatorPulseLocal: "bg-emerald-400",
    runtimeIndicatorPulseCloud: "bg-sky-400",
    runtimeIndicatorDot: "relative inline-flex h-2 w-2 rounded-full",
    runtimeIndicatorDotLocal: "bg-emerald-500",
    runtimeIndicatorDotCloud: "bg-sky-500",
  },
  footer: {
    root: "flex items-center justify-between border-t border-zinc-100 bg-white px-10 py-5 z-10",
    statusWrap: "text-sm font-medium",
    statusRow: "flex items-center gap-2",
    statusSaving: "text-zinc-500",
    statusError: "text-red-600",
    statusSaved: "text-emerald-600",
    statusChanged: "text-amber-600",
    statusSynced: "text-zinc-400",
    icon: "h-4 w-4",
    iconSpinning: "h-4 w-4 animate-spin",
    changedIndicatorWrap: "relative flex h-2 w-2",
    changedIndicatorPulse:
      "absolute inline-flex h-full w-full animate-ping rounded-full bg-amber-400 opacity-75",
    changedIndicatorDot: "relative inline-flex h-2 w-2 rounded-full bg-amber-500",
    actions: "flex items-center gap-3",
    resetButton:
      "inline-flex h-9 items-center justify-center rounded-lg px-4 text-[14px] font-medium text-zinc-600 transition-colors hover:bg-zinc-100 hover:text-zinc-900 active:scale-[0.98] disabled:cursor-not-allowed disabled:text-zinc-300 disabled:hover:bg-transparent",
    saveButton:
      "inline-flex h-9 items-center justify-center rounded-lg px-5 text-[14px] font-medium transition-all active:scale-[0.98] shadow-sm",
    saveButtonEnabled: "bg-zinc-900 text-white hover:bg-zinc-800 hover:shadow",
    saveButtonDisabled: "cursor-not-allowed bg-zinc-100 text-zinc-400 shadow-none transform-none",
  },
  field: {
    infoCard: "rounded-xl px-4 py-3 text-[14px] leading-relaxed shadow-sm",
    infoCardNeutral: "bg-white text-zinc-600 border border-zinc-200",
    infoCardWarning: "bg-amber-50 text-amber-700 border border-amber-200",
    divider: "flex items-center justify-between pb-1",
    dividerDefaultSpacing: "mb-0 mt-8",
    dividerCompactSpacing: "mb-0",
    dividerTitle: "text-[15px] font-semibold text-zinc-900",
    dividerAccent: "hidden",
    iconButton:
      "absolute right-2.5 top-1/2 inline-flex h-7 w-7 -translate-y-1/2 items-center justify-center rounded-md p-1 text-zinc-400 transition-colors hover:text-zinc-700",
    icon: "h-4 w-4",
    card: "rounded-xl border border-zinc-200/80 bg-white shadow-sm overflow-hidden",
    cardBody: "",
    labelBlock: "flex flex-col gap-0.5 min-w-0 md:w-[200px] shrink-0",
    label: "text-[14px] font-medium text-zinc-900",
    description: "text-[13px] leading-relaxed text-zinc-500",
    note: "text-[12px] leading-relaxed text-zinc-400",
    readonlyValue:
      "w-full max-w-full break-all rounded-md border border-zinc-200 bg-zinc-50 px-3 py-2 font-mono text-[13px] text-zinc-600",
    control:
      "min-h-[40px] w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-[14px] text-zinc-900 transition-colors placeholder:text-zinc-400 hover:border-zinc-400 focus-visible:outline-none focus-visible:border-zinc-900 focus-visible:ring-1 focus-visible:ring-zinc-900 disabled:cursor-not-allowed disabled:opacity-50 disabled:bg-zinc-50",
    select:
      "appearance-none items-center justify-between whitespace-nowrap cursor-pointer bg-[url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M6%209L12%2015L18%209%22%20stroke%3D%22%2371717A%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%3C%2Fsvg%3E')] bg-[length:16px_16px] bg-[position:right_10px_center] bg-no-repeat pr-10",
    switchRow:
      "flex flex-row items-center justify-between w-full py-5 transition-colors",
    switchCopy: "flex flex-col gap-1 pr-4",
    switchLabel: "cursor-pointer text-[14px] font-medium text-zinc-900",
    switchDescription: "text-[13px] leading-relaxed text-zinc-500",
    switchButton:
      "relative inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500/30 focus-visible:ring-offset-2",
    switchButtonEnabled: "bg-emerald-500",
    switchButtonDisabled: "bg-zinc-200",
    switchThumb:
      "pointer-events-none block h-5 w-5 rounded-full bg-white shadow-[0_1px_2px_rgba(0,0,0,0.15)] ring-0 transition-transform",
    switchThumbEnabled: "translate-x-5",
    switchThumbDisabled: "translate-x-0",
  },
  list: {
    root: "flex flex-col divide-y divide-zinc-100",
    item: "settings-row flex flex-col gap-6 py-5 transition-colors md:flex-row md:items-start",
    controlWrap: "flex-1 min-w-0 w-full",
    readonlyItem: "settings-row flex flex-col gap-6 py-5 md:flex-row md:items-start",
    readonlyControl: "flex-1 min-w-0 w-full",
  },
  section: {
    root: "space-y-10",
    groupBlock: "",
    cardWrapper: "flex flex-col divide-y divide-zinc-100",
    mixedBlock: "space-y-6",
  },
} as const;

export const SETTING_SELECT_OPTIONS: Record<
  string,
  Array<{ value: string; label: string }>
> = {
  "llm.provider": [
    { value: "", label: "自动识别" },
    { value: "openai_compatible", label: "OpenAI Compatible" },
    { value: "openai", label: "OpenAI" },
    { value: "azure", label: "Azure OpenAI" },
    { value: "anthropic", label: "Anthropic" },
    { value: "gemini", label: "Gemini" },
    { value: "vertex_ai", label: "Vertex AI" },
    { value: "qwen", label: "Qwen / DashScope" },
    { value: "deepseek", label: "DeepSeek" },
    { value: "kimi", label: "Kimi / Moonshot" },
    { value: "glm", label: "GLM / Zhipu" },
    { value: "minimax", label: "MiniMax" },
    { value: "doubao", label: "Doubao" },
    { value: "siliconflow", label: "SiliconFlow" },
    { value: "openrouter", label: "OpenRouter" },
    { value: "vllm", label: "vLLM" },
    { value: "ollama", label: "Ollama" },
    { value: "xai", label: "xAI / Grok" },
    { value: "groq", label: "Groq" },
    { value: "mistral", label: "Mistral" },
    { value: "bedrock", label: "AWS Bedrock" },
  ],
  "planner.default_digest_mode": [
    { value: "sprint", label: "sprint" },
    { value: "systematic", label: "systematic" },
  ],
};
