"""Examine Engine 提示词模块。

集中导出各阶段系统提示词与模板映射，其他模块可直接 from prompts import。
"""

from .prompts import (
    PROMPTS,
    SYSTEM_PROMPT_ERROR_CAUSE_LABEL,
    SYSTEM_PROMPT_EXAM_GENERATE,
    SYSTEM_PROMPT_EXAM_GENERATE_FROM_TEXT,
    SYSTEM_PROMPT_MISTAKE_ANALYSIS,
    SYSTEM_PROMPT_SHORT_ANSWER_GRADE,
)

__all__ = [
    "SYSTEM_PROMPT_EXAM_GENERATE",
    "SYSTEM_PROMPT_EXAM_GENERATE_FROM_TEXT",
    "SYSTEM_PROMPT_SHORT_ANSWER_GRADE",
    "SYSTEM_PROMPT_ERROR_CAUSE_LABEL",
    "SYSTEM_PROMPT_MISTAKE_ANALYSIS",
    "PROMPTS",
]
