"""Knowledge-domain API schemas."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from app.schemas.common import PageParams


# Requests


class DigestBuildRequest(BaseModel):
    """Trigger incremental digest build."""

    model_config = ConfigDict(
        json_schema_extra={"example": {"file_ids": [1, 2], "idempotency_key": "abc123"}}
    )

    file_ids: list[int] = Field(min_length=1, description="Parsed raw file IDs for this build.")
    idempotency_key: str | None = Field(
        default=None,
        description="Optional idempotency key; generated by backend when omitted.",
    )


class DigestStatusRequest(BaseModel):
    """Get digest job status."""

    job_id: int = Field(description="GraphDigestJob ID.")


class DocGenBuildRequest(BaseModel):
    """Trigger knowledge-doc generation."""

    model_config = ConfigDict(
        json_schema_extra={"example": {"file_ids": [1, 2], "prompt": "Generate review-oriented notes"}}
    )

    file_ids: list[int] | None = Field(
        default=None,
        description="Optional parsed raw file IDs; omitted means auto-pick all available files for the subject.",
    )
    prompt: str | None = Field(default=None, description="Optional user instruction for doc generation.")


class GraphNodesQueryRequest(PageParams):
    """Paginated graph node query."""

    node_type: str | None = Field(default=None, description="Optional node type filter.")


class GraphNodeDetailRequest(BaseModel):
    """Node detail query."""

    node_id: int = Field(description="Knowledge node ID.")


class KnowledgeOverviewRequest(BaseModel):
    """Aggregated knowledge overview query."""

    include: list[str] | None = Field(
        default=None,
        description="Optional sections to include. Omit for default full payload.",
    )
    full: bool = Field(
        default=True,
        description="Whether to return full payload. Current implementation favors full payload.",
    )


class ChunkContextRequest(BaseModel):
    """Chat chunk context query."""

    chunk_id: int = Field(description="Document chunk ID.")


class UnitsQueryRequest(PageParams):
    """Paginated teaching-unit query."""

    status: str | None = Field(default=None, description="Optional status filter; defaults to active.")


class UnitDetailRequest(BaseModel):
    """Teaching-unit detail query."""

    unit_id: int = Field(description="Teaching unit ID.")


class AnchorManageRequest(BaseModel):
    """Taxonomy anchor management request."""

    action: str = Field(description="list / create / update / delete")
    anchor_id: int | None = Field(default=None, description="Anchor ID for update/delete.")
    title: str | None = Field(default=None, description="Anchor title for create/update.")
    anchor_type: str | None = Field(
        default=None,
        description="teacher_defined / syllabus / textbook_toc / graph_discovered",
    )
    parent_anchor_id: int | None = Field(default=None, description="Parent anchor ID.")
    order_index: int | None = Field(default=None, description="Order index.")


# Responses


class DigestBuildData(BaseModel):
    """Digest build trigger response payload."""

    message: str = Field(description="Build trigger confirmation message.")


class CurriculumJobResponse(BaseModel):
    """Curriculum derive job status."""

    id: int
    subject: str
    status: str
    units_added: int = 0
    units_updated: int = 0
    theme_tree_version_id: int | None = None
    prereq_dag_version_id: int | None = None
    error_message: str | None = None
    created_at: datetime
    updated_at: datetime


class DocGenBuildData(BaseModel):
    """Doc-gen build trigger response payload."""

    job_id: int = Field(description="DocGenJob ID.")
    accepted_file_ids: list[int] = Field(default_factory=list, description="Accepted raw file IDs.")
    prompt: str | None = Field(default=None, description="User prompt.")
    ready_file_count: int = Field(default=0, description="Total available ready files at trigger time.")


class DocGenJobResponse(BaseModel):
    """Doc-gen job status."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    subject: str
    status: str
    progress: int
    current_step: str | None = None
    total_chapters: int = 0
    completed_chapters: int = 0
    error_message: str | None = None
    created_at: datetime
    updated_at: datetime


class DocGenGetResponse(BaseModel):
    """Doc-gen aggregated response."""

    exists: bool = Field(description="Whether merged markdown exists.")
    markdown: str = Field(default="", description="Merged markdown content.")
    merged_path: str | None = Field(default=None, description="Local merged markdown path.")
    updated_at: datetime | None = Field(default=None, description="Merged markdown mtime.")
    job: DocGenJobResponse | None = Field(default=None, description="Latest DocGen job.")
    source_file_ids: list[int] = Field(default_factory=list, description="Source raw file IDs.")
    prompt: str | None = Field(default=None, description="User prompt.")


class DigestStatusResponse(BaseModel):
    """Digest status aggregate: curriculum job + snapshot pointer."""

    curriculum_job: CurriculumJobResponse | None = None
    current_curriculum_snapshot_id: int | None = None


class KnowledgeNodeResponse(BaseModel):
    """Knowledge node list item."""

    id: int
    subject: str
    node_type: str
    canonical_name: str
    status: str
    confidence: float
    created_at: datetime
    updated_at: datetime


class EvidenceSummary(BaseModel):
    """Evidence summary used in node detail."""

    id: int
    document_id: int
    chunk_id: int
    quote_text: str
    evidence_role: str
    field_scope: str
    confidence: float


class ChunkContextResponse(BaseModel):
    """Chat chunk context response."""

    chunk_id: int
    document_id: int
    document_title: str
    chunk_title: str
    chunk_header_path: str
    chunk_content: str


class AliasItem(BaseModel):
    """Node alias item."""

    id: int
    alias: str
    language: str
    source: str
    confidence: float
    is_primary: bool


class IncidentEdgeItem(BaseModel):
    """Incident edge item."""

    id: int
    edge_type: str
    direction: str = Field(description="outgoing or incoming.")
    other_node_id: int
    other_node_name: str
    other_node_type: str
    confidence: float


class NodeRevisionItem(BaseModel):
    """Current revision content for a knowledge node."""

    title: str
    summary: str
    body: str


class KnowledgeNodeDetailResponse(BaseModel):
    """Knowledge node detail response."""

    id: int
    subject: str
    node_type: str
    canonical_name: str
    normalized_name: str
    status: str
    confidence: float
    current_revision: NodeRevisionItem | None = None
    aliases: list[AliasItem] = Field(default_factory=list)
    evidence: list[EvidenceSummary] = Field(default_factory=list)
    incident_edges: list[IncidentEdgeItem] = Field(default_factory=list)
    created_at: datetime
    updated_at: datetime


class UnitMembershipItem(BaseModel):
    """Teaching-unit membership item."""

    id: int
    knowledge_node_id: int
    node_canonical_name: str
    node_type: str
    role: str
    score: float


class UnitRevisionItem(BaseModel):
    """Current revision for a teaching unit."""

    title: str
    summary: str
    learning_objectives: list[str] = Field(default_factory=list)


class TeachingUnitResponse(BaseModel):
    """Teaching-unit list item."""

    id: int
    subject: str
    canonical_name: str
    status: str
    confidence: float
    created_at: datetime
    updated_at: datetime


class TeachingUnitDetailResponse(BaseModel):
    """Teaching-unit detail response."""

    id: int
    subject: str
    canonical_name: str
    normalized_name: str
    member_signature: str
    status: str
    confidence: float
    current_revision: UnitRevisionItem | None = None
    members: list[UnitMembershipItem] = Field(default_factory=list)
    created_at: datetime
    updated_at: datetime


class TaxonomyAnchorResponse(BaseModel):
    """Taxonomy anchor response."""

    id: int
    subject: str
    anchor_type: str
    title: str
    parent_anchor_id: int | None = None
    order_index: int
    confidence: float
    is_system: bool
    status: str
    created_at: datetime
    updated_at: datetime


class ThemeTreeNodeResponse(BaseModel):
    """Theme-tree node response."""

    id: int
    tree_version_id: int
    anchor_id: int | None = None
    parent_tree_node_id: int | None = None
    title: str
    node_type: str
    order_index: int
    summary: str
    children: list["ThemeTreeNodeResponse"] = Field(default_factory=list)
    units: list["TreeUnitItem"] = Field(default_factory=list)


class TreeUnitItem(BaseModel):
    """Teaching-unit mount info in theme tree."""

    teaching_unit_id: int
    canonical_name: str
    membership_role: str
    membership_source: str
    score: float


class ThemeTreeResponse(BaseModel):
    """Current published theme tree response."""

    version_id: int
    version_no: int
    subject: str
    status: str
    created_at: datetime
    tree: list[ThemeTreeNodeResponse] = Field(default_factory=list)


class CurriculumSnapshotResponse(BaseModel):
    """Current curriculum snapshot response."""

    id: int
    subject: str
    version_no: int
    status: str
    theme_tree_version_id: int | None = None
    prereq_dag_version_id: int | None = None
    syllabus_version_id: int | None = None
    created_at: datetime


class UnitDependencyItem(BaseModel):
    """Dependency edge item in prereq DAG."""

    id: int
    source_unit_id: int
    source_unit_name: str
    target_unit_id: int
    target_unit_name: str
    dependency_type: str
    confidence: float
    supporting_edge_count: int


class PrereqDagResponse(BaseModel):
    """Current published prereq DAG response."""

    version_id: int
    version_no: int
    subject: str
    status: str
    created_at: datetime
    dependencies: list[UnitDependencyItem] = Field(default_factory=list)


class GraphEdgeResponse(BaseModel):
    """Graph edge item used by full-graph query."""

    id: int
    source_node_id: int
    target_node_id: int
    edge_type: str
    weight: float
    confidence: float


class FullGraphResponse(BaseModel):
    """Full graph payload for force-graph visualization."""

    nodes: list[KnowledgeNodeResponse] = Field(default_factory=list)
    edges: list[GraphEdgeResponse] = Field(default_factory=list)


class KnowledgeOverviewStats(BaseModel):
    """Knowledge overview stats."""

    node_count: int = 0
    edge_count: int = 0
    unit_count: int = 0
    theme_node_count: int = 0
    dependency_count: int = 0


class KnowledgeOverviewResponse(BaseModel):
    """Knowledge overview aggregated payload for summary tabs."""

    subject: str
    generated_at: datetime
    snapshot: CurriculumSnapshotResponse | None = None
    theme_tree: ThemeTreeResponse | None = None
    prereq_dag: PrereqDagResponse | None = None
    graph: FullGraphResponse | None = None
    units: list[TeachingUnitResponse] = Field(default_factory=list)
    stats: KnowledgeOverviewStats = Field(default_factory=KnowledgeOverviewStats)


class ClearKnowledgeResponse(BaseModel):
    """Knowledge clear response."""

    subject: str
    deleted_counts: dict[str, int] = Field(default_factory=dict)


ThemeTreeNodeResponse.model_rebuild()
