"""Code-owned ingest parsing defaults outside the project settings surface."""

from __future__ import annotations

DEFAULT_PARSE_CONCURRENCY = 5
DEFAULT_PARSER_TIMEOUT_S = 90
DEFAULT_MINERU_MODEL_VERSION = "vlm"
DEFAULT_MINERU_ENABLE_FORMULA = True
DEFAULT_MINERU_ENABLE_TABLE = True
DEFAULT_MINERU_IS_OCR = False

__all__ = [
    "DEFAULT_MINERU_ENABLE_FORMULA",
    "DEFAULT_MINERU_ENABLE_TABLE",
    "DEFAULT_MINERU_IS_OCR",
    "DEFAULT_MINERU_MODEL_VERSION",
    "DEFAULT_PARSE_CONCURRENCY",
    "DEFAULT_PARSER_TIMEOUT_S",
]
