"""Shared preparation layer for unified digest build."""

from app.workflows.digest.shared.contracts import (
    DEFAULT_COURSE_TYPE,
    DigestBuildConstraints,
    DigestChapterContract,
    DigestChapterMediaHints,
    DigestConfirmedPlanContract,
    PLANNER_RETRIEVAL_PROFILE,
    SPRINT_COURSE_TYPE,
    normalize_digest_confirmed_plan_payload,
    parse_digest_confirmed_plan_contract,
    resolve_digest_course_type,
    resolve_digest_retrieval_profile,
    resolve_planner_retrieval_profile,
    resolve_teaching_action,
)
from app.workflows.digest.shared.models import (
    AssetItem,
    AssetRegistry,
    ChunkIdentityMap,
    DigestMode,
    DigestModeDecision,
    FastTopicHints,
    MaterialProfile,
    MaterialStats,
    SectionPacket,
    SharedInputs,
    SourcePacket,
)
from app.workflows.digest.shared.metrics import (
    DigestModelUsageSummary,
    DigestTimingReport,
    DigestTokenSummary,
    SlowItemTiming,
    add_slow_item,
    build_lane_llm_rollup,
    build_lane_step_slow_items,
    build_slow_items,
    build_token_summary,
    step_slow_items,
)
from app.workflows.digest.shared.material_profile import (
    build_material_profile,
    compute_material_stats,
    decide_digest_mode,
)
from app.workflows.digest.shared.prepare import prepare_shared_inputs

__all__ = [
    "AssetItem",
    "AssetRegistry",
    "ChunkIdentityMap",
    "DEFAULT_COURSE_TYPE",
    "DigestBuildConstraints",
    "DigestChapterContract",
    "DigestChapterMediaHints",
    "DigestConfirmedPlanContract",
    "DigestMode",
    "DigestModeDecision",
    "DigestModelUsageSummary",
    "DigestTimingReport",
    "DigestTokenSummary",
    "FastTopicHints",
    "MaterialProfile",
    "MaterialStats",
    "normalize_digest_confirmed_plan_payload",
    "parse_digest_confirmed_plan_contract",
    "PLANNER_RETRIEVAL_PROFILE",
    "SectionPacket",
    "SharedInputs",
    "SlowItemTiming",
    "SourcePacket",
    "SPRINT_COURSE_TYPE",
    "add_slow_item",
    "build_lane_llm_rollup",
    "build_lane_step_slow_items",
    "build_material_profile",
    "build_slow_items",
    "build_token_summary",
    "compute_material_stats",
    "decide_digest_mode",
    "prepare_shared_inputs",
    "resolve_digest_course_type",
    "resolve_digest_retrieval_profile",
    "resolve_planner_retrieval_profile",
    "resolve_teaching_action",
    "step_slow_items",
]
