"""Shared preparation layer for digest build."""

from app.workflows.digest.common.contracts import (
    DEFAULT_DIGEST_MODE,
    DigestBuildConstraints,
    DigestChapterContract,
    DigestConfirmedPlanContract,
    PLANNER_RETRIEVAL_PROFILE,
    SPRINT_DIGEST_MODE,
    normalize_digest_confirmed_plan_payload,
    parse_digest_confirmed_plan_contract,
    normalize_digest_mode,
    resolve_digest_retrieval_profile,
    resolve_planner_retrieval_profile,
    resolve_teaching_action,
)
from app.workflows.digest.common.models import (
    AssetItem,
    AssetRegistry,
    ChunkIdentityMap,
    DigestMaterialContext,
    DigestMode,
    DigestModeDecision,
    FastTopicHints,
    MaterialProfile,
    MaterialStats,
    SectionPacket,
    SharedInputs,
    SourcePacket,
)
from app.workflows.digest.common.metrics import (
    DigestModelUsageSummary,
    DigestTimingReport,
    DigestTokenSummary,
    SlowItemTiming,
    add_slow_item,
    build_lane_llm_rollup,
    build_lane_step_slow_items,
    build_slow_items,
    build_token_summary,
    step_slow_items,
)
from app.workflows.digest.common.material_profile import (
    build_material_profile,
    compute_material_stats,
    decide_digest_mode,
)
from app.workflows.digest.common.prepare import prepare_material_context, prepare_shared_inputs
from app.workflows.digest.common.cleanup import clear_subject_knowledge

__all__ = [
    "AssetItem",
    "AssetRegistry",
    "ChunkIdentityMap",
    "DEFAULT_DIGEST_MODE",
    "DigestBuildConstraints",
    "DigestChapterContract",
    "DigestConfirmedPlanContract",
    "DigestMode",
    "DigestModeDecision",
    "DigestMaterialContext",
    "DigestModelUsageSummary",
    "DigestTimingReport",
    "DigestTokenSummary",
    "FastTopicHints",
    "MaterialProfile",
    "MaterialStats",
    "normalize_digest_confirmed_plan_payload",
    "parse_digest_confirmed_plan_contract",
    "PLANNER_RETRIEVAL_PROFILE",
    "SectionPacket",
    "SharedInputs",
    "SlowItemTiming",
    "SourcePacket",
    "SPRINT_DIGEST_MODE",
    "add_slow_item",
    "build_lane_llm_rollup",
    "build_lane_step_slow_items",
    "build_material_profile",
    "build_slow_items",
    "build_token_summary",
    "clear_subject_knowledge",
    "compute_material_stats",
    "decide_digest_mode",
    "prepare_shared_inputs",
    "prepare_material_context",
    "normalize_digest_mode",
    "resolve_digest_retrieval_profile",
    "resolve_planner_retrieval_profile",
    "resolve_teaching_action",
    "step_slow_items",
]
