import type { LucideIcon } from "lucide-react";
import {
  AudioLines,
  Atom,
  Backpack,
  BadgeCheck,
  Banknote,
  Beaker,
  Binary,
  BookMarked,
  BookOpen,
  BookText,
  Bot,
  Braces,
  Brain,
  BriefcaseBusiness,
  Brush,
  Building2,
  Calculator,
  Camera,
  ChartBar,
  ChartLine,
  ChartPie,
  CircuitBoard,
  Code,
  ClipboardCheck,
  Cog,
  Compass,
  Cpu,
  Database,
  Dna,
  DraftingCompass,
  Earth,
  Factory,
  Feather,
  FileQuestion,
  FileText,
  Files,
  Film,
  Flower2,
  FlaskConical,
  Globe,
  GitBranch,
  GraduationCap,
  Gavel,
  HandCoins,
  Hammer,
  HardHat,
  HeartPulse,
  Infinity as InfinityIcon,
  KeyRound,
  Landmark,
  LandPlot,
  Languages,
  Leaf,
  Library,
  LockKeyhole,
  Magnet,
  Map,
  MapPinned,
  Medal,
  MessageCircle,
  Microscope,
  Mountain,
  Music,
  Network,
  Newspaper,
  NotebookPen,
  NotebookTabs,
  Palette,
  Paintbrush,
  PenTool,
  Pencil,
  Pill,
  Piano,
  Route,
  Router,
  Rocket,
  Ruler,
  Satellite,
  Scale,
  ScanHeart,
  School,
  ScrollText,
  Scroll,
  Server,
  ShieldCheck,
  Shapes,
  Sigma,
  Speech,
  SquareFunction,
  Sprout,
  Stethoscope,
  Telescope,
  Terminal,
  TestTube,
  Trophy,
  Video,
  Vote,
  Wallet,
  Workflow,
  Wrench,
} from "lucide-react";

export const COURSE_ICON_MAP: Record<string, LucideIcon> = {
  "book-open": BookOpen,
  "book-marked": BookMarked,
  "book-text": BookText,
  "notebook-tabs": NotebookTabs,
  "notebook-pen": NotebookPen,
  library: Library,
  newspaper: Newspaper,
  "graduation-cap": GraduationCap,
  school: School,
  backpack: Backpack,
  calculator: Calculator,
  sigma: Sigma,
  ruler: Ruler,
  compass: Compass,
  "square-function": SquareFunction,
  infinity: InfinityIcon,
  "flask-conical": FlaskConical,
  "test-tube": TestTube,
  beaker: Beaker,
  atom: Atom,
  magnet: Magnet,
  "circuit-board": CircuitBoard,
  microscope: Microscope,
  dna: Dna,
  stethoscope: Stethoscope,
  pill: Pill,
  "heart-pulse": HeartPulse,
  brain: Brain,
  "scan-heart": ScanHeart,
  code: Code,
  braces: Braces,
  terminal: Terminal,
  binary: Binary,
  cpu: Cpu,
  database: Database,
  server: Server,
  network: Network,
  router: Router,
  "shield-check": ShieldCheck,
  "key-round": KeyRound,
  "lock-keyhole": LockKeyhole,
  bot: Bot,
  workflow: Workflow,
  "git-branch": GitBranch,
  languages: Languages,
  speech: Speech,
  "message-circle": MessageCircle,
  "pen-tool": PenTool,
  pencil: Pencil,
  feather: Feather,
  "scroll-text": ScrollText,
  "file-text": FileText,
  "file-question": FileQuestion,
  files: Files,
  "clipboard-check": ClipboardCheck,
  "badge-check": BadgeCheck,
  medal: Medal,
  trophy: Trophy,
  landmark: Landmark,
  scale: Scale,
  gavel: Gavel,
  scroll: Scroll,
  vote: Vote,
  globe: Globe,
  earth: Earth,
  map: Map,
  "map-pinned": MapPinned,
  route: Route,
  "land-plot": LandPlot,
  mountain: Mountain,
  palette: Palette,
  brush: Brush,
  paintbrush: Paintbrush,
  shapes: Shapes,
  "drafting-compass": DraftingCompass,
  music: Music,
  piano: Piano,
  "audio-lines": AudioLines,
  camera: Camera,
  film: Film,
  video: Video,
  "briefcase-business": BriefcaseBusiness,
  "building-2": Building2,
  factory: Factory,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  "chart-bar": ChartBar,
  wallet: Wallet,
  banknote: Banknote,
  "hand-coins": HandCoins,
  wrench: Wrench,
  hammer: Hammer,
  cog: Cog,
  "hard-hat": HardHat,
  telescope: Telescope,
  rocket: Rocket,
  satellite: Satellite,
  leaf: Leaf,
  sprout: Sprout,
  "flower-2": Flower2,
};

export function resolveCourseIcon(iconKey?: string | null): LucideIcon {
  return COURSE_ICON_MAP[String(iconKey || "").trim()] ?? BookOpen;
}
